version: 2
models:
  - name: stg_commandes
    description: "Commandes nettoyées et typées"
    columns:
      - name: commande_id
        tests: [unique, not_null]
      - name: statut
        tests:
          - accepted_values:
              values: ['nouvelle', 'validee', 'en_cours', 'livree', 'annulee']

  - name: stg_livreurs
    description: "Livreurs nettoyés"
    columns:
      - name: livreur_id
        tests: [unique, not_null]

  - name: stg_statuts_livraison
    description: "Historique des statuts de livraison"
    columns:
      - name: statut_id
        tests: [unique, not_null]