version: 2
sources:
  - name: livraison_raw
    description: "Tables brutes de l'application de livraison"
    database: livraison_db
    schema: public
    tables:
      - name: commande
      - name: livreur
      - name: statut_livraison
      - name: incident